import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { HeroBanner } from "@/components/HeroBanner";


const inter = Inter({
	variable: "--font-inter",
	subsets: ["vietnamese"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	display: "swap",
});


export const metadata: Metadata = {
	title: "Login",
	description: "Generated by create next app",
};

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
				<div className="min-h-screen flex items-center justify-center">
					<div className="flex w-[1300px] h-[900px]">
						<div className="flex-1 flex items-center justify-center">{children}</div>
						<div className="flex-1 hidden lg:flex items-center justify-start">
							<HeroBanner />
						</div>
					</div>
				</div>

	);
}
