import type { Metadata } from "next";
import { Inter, Monsieur_La_Doulaise } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "sonner";



const inter = Inter({
	variable: "--font-inter",
	subsets: ["vietnamese"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	display: "swap",
});

const monsieur = Monsieur_La_Doulaise({
	variable: "--font-mosieur",
	subsets: ["latin"],
	weight: ["400"],
	display: "swap",
});


export const metadata: Metadata = {
	title: "Hoang Ha App",
	description: "Generated by create next app",
};

export default function AdminLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// Nested admin layout — do not render <html> or <body> here.
	// The root layout handles font variables and body classes.
	return (
		<html lang="en">
			<body className={`${inter.variable} ${monsieur.variable} antialiased`}>
				<>
					{children}
					<Toaster/>
				</>
			</body>
		</html>
	);
}
